<?xml version="1.0" encoding="UTF-8"?>
<ck><di ky="884" rd="surface_and_polysurface_methods/addnurbssurface.htm|AddNurbsSurface" ct=" AddNurbsSurface  Adds a NURBS surface object to the document.  Syntax  Rhino.AddNurbsSurfac ..."/><di ky="885" rd="surface_and_polysurface_methods/addpatch.htm|AddPatch" ct=" AddPatch  Fits a surface through curve, point, point cloud, and mesh objects.  Syntax  Rhin ..."/><di ky="886" rd="surface_and_polysurface_methods/addpipe.htm|AddPipe" ct=" AddPipe  Creates a singled-walled surface with a circular profile around a curve.  Syntax  ..."/><di ky="887" rd="surface_and_polysurface_methods/addplanarsrf.htm|AddPlanarSrf" ct=" AddPlanarSrf  Creates one or more surfaces from planar curves.  Syntax  Rhino.AddPlanarSrf  ..."/><di ky="888" rd="surface_and_polysurface_methods/addplanesurface.htm|AddPlaneSurface" ct=" AddPlaneSurface  Creates a plane surface.  Syntax  Rhino.AddPlaneSurface (arrPlane, dblDU,  ..."/><di ky="889" rd="surface_and_polysurface_methods/addrailrevsrf.htm|AddRailRevSrf" ct=" AddRailRevSrf  Create a surface by revolving a profile curve along a rail curve.  Syntax  R ..."/><di ky="890" rd="surface_and_polysurface_methods/addrevsrf.htm|AddRevSrf" ct=" AddRevSrf  Create a surface by revolving a curve around an axis.  Syntax  Rhino.AddRevSrf ( ..."/><di ky="891" rd="surface_and_polysurface_methods/addsphere.htm|AddSphere" ct=" AddSphere  Adds a spherical surface to the document.  Syntax  Rhino.AddSphere (arrCen ..."/><di ky="892" rd="surface_and_polysurface_methods/addsrfcontourcrvs.htm|AddSrfContourCrvs" ct=" AddSrfContourCrvs  Adds a spaced series of planar curves resulting from the intersection of a d ..."/><di ky="893" rd="surface_and_polysurface_methods/addsrfcontrolptgrid.htm|AddSrfControlPtGrid" ct=" AddSrfControlPtGrid  Creates a surface from a grid of control points.  Syntax  Rhino.AddSrf ..."/><di ky="894" rd="surface_and_polysurface_methods/addsrfpt.htm|AddSrfPt" ct=" AddSrfPt  Creates a new surface from either 3 or 4 corner points.  Syntax  Rhino.AddSrfPt ( ..."/><di ky="895" rd="surface_and_polysurface_methods/addsrfptgrid.htm|AddSrfPtGrid" ct=" AddSrfPtGrid  Creates a surface from a grid of points.  Syntax  Rhino.AddSrfPtGrid (arrCoun ..."/><di ky="896" rd="surface_and_polysurface_methods/addsrfsectioncrvs.htm|AddSrfSectionCrvs" ct=" AddSrfSectionCrvs  Adds planar curves resulting from the intersection of a defined cutting plan ..."/><di ky="897" rd="surface_and_polysurface_methods/addsweep1.htm|AddSweep1" ct=" AddSweep1  Adds a surface created through profile curves that define the surface shape and one  ..."/><di ky="898" rd="surface_and_polysurface_methods/addsweep2.htm|AddSweep2" ct=" AddSweep2  Adds a surface created through profile curves that define the surface shape and two  ..."/><di ky="899" rd="surface_and_polysurface_methods/addthickpipe.htm|AddThickPipe" ct=" AddThickPipe  Creates a double-walled surface with a circular profile around a curve.  Syntax ..."/><di ky="900" rd="surface_and_polysurface_methods/addtorus.htm|AddTorus" ct=" AddTorus  Adds a torus-shaped revolved surface to the document.  Syntax  Rhino.AddTorus (ar ..."/><di ky="901" rd="surface_and_polysurface_methods/addtruncatedcone.htm|AddTruncatedCone" ct=" AddTruncatedCone  Adds a truncated cone-shaped polysurface to the document.  Syntax  Rhino. ..."/><di ky="902" rd="surface_and_polysurface_methods/booleandifference.htm|BooleanDifference" ct=" BooleanDifference  Performs a Boolean difference operation on two sets of input surfaces and po ..."/><di ky="903" rd="surface_and_polysurface_methods/booleanintersection.htm|BooleanIntersection" ct=" BooleanIntersection  Performs a Boolean intersection operation on two sets of input surfaces an ..."/><di ky="904" rd="surface_and_polysurface_methods/booleanunion.htm|BooleanUnion" ct=" BooleanUnion  Performs a Boolean union operation on a set of input surfaces and polysurfaces. F ..."/><di ky="905" rd="surface_and_polysurface_methods/boxpoints.htm|BoxPoints" ct=" BoxPoints  Returns the corner points of a polysurface box. Points are returned  in counter-cl ..."/><di ky="906" rd="surface_and_polysurface_methods/brepclosestpoint.htm|BrepClosestPoint" ct=" BrepClosestPoint  Returns the point on a surface or polysurface that is closest to a test  po ..."/><di ky="907" rd="surface_and_polysurface_methods/capplanarholes.htm|CapPlanarHoles" ct=" CapPlanarHoles  Caps planar holes in a surface or polysurface. For more details, see the  Cap   ..."/><di ky="908" rd="surface_and_polysurface_methods/convertextrusion.htm|ConvertExtrusion" ct=" ConvertExtrusion  Converts an extrusion object to a surface and polysurface object.  Syntax  ..."/><di ky="909" rd="surface_and_polysurface_methods/convertsurfacetobezier.htm|ConvertSurfaceToBezier" ct=" ConvertSurfaceToBezier  Changes the structure of a NURBS surface to a Bézier surface.  Syntax ..."/><di ky="910" rd="surface_and_polysurface_methods/createsolid.htm|CreateSolid" ct=" CreateSolid  Creates a closed polysurface from surfaces and polysurfaces that bound  a region ..."/><di ky="911" rd="surface_and_polysurface_methods/duplicateedgecurves.htm|DuplicateEdgeCurves" ct=" DuplicateEdgeCurves  Duplicates the edge curves of a surface or polysurface. For more informati ..."/><di ky="912" rd="surface_and_polysurface_methods/duplicatesurfaceborder.htm|DuplicateSurfaceBorder" ct=" DuplicateSurfaceBorder  Creates a curve that duplicates a surface or polysurface border.  Syn ..."/><di ky="913" rd="surface_and_polysurface_methods/evaluatesurface.htm|EvaluateSurface" ct=" EvaluateSurface  Evaluates a surface at a U,V parameter.  Syntax  Rhino.EvaluateSurface (st ..."/><di ky="914" rd="surface_and_polysurface_methods/explodepolysurfaces.htm|ExplodePolysurfaces" ct=" ExplodePolysurfaces  Explodes, or un-joins,  one more polysurface objects.  Polysurfaces will b ..."/><di ky="915" rd="surface_and_polysurface_methods/extendsurface.htm|ExtendSurface" ct=" ExtendSurface  Lengthens an untrimmed surface object by a factor value.  Syntax  Rhino.Exte ..."/><di ky="916" rd="surface_and_polysurface_methods/extractisocurve.htm|ExtractIsoCurve" ct=" ExtractIsoCurve  Extracts isoparametric curves from a surface.  Syntax  Rhino.ExtractIsoCur ..."/><di ky="917" rd="surface_and_polysurface_methods/extractsurface.htm|ExtractSurface" ct=" ExtractSurface  Separates or copies a surface (face) or a copy of a surface from a polysurface. ..."/><di ky="918" rd="surface_and_polysurface_methods/extrudecurve.htm|ExtrudeCurve" ct=" ExtrudeCurve  Creates a surface by extruding a curve along a path curve.  Syntax  Rhino.Ext ..."/><di ky="919" rd="surface_and_polysurface_methods/extrudecurvenormal.htm|ExtrudeCurveNormal" ct=" ExtrudeCurveNormal  Extrudes a curve, that lies on a surface, normal to the surface. This  is ..."/><di ky="920" rd="surface_and_polysurface_methods/extrudecurvepoint.htm|ExtrudeCurvePoint" ct=" ExtrudeCurvePoint  Creates a surface by extruding a curve to a point.  Syntax  Rhino.Extrud ..."/><di ky="921" rd="surface_and_polysurface_methods/extrudecurvestraight.htm|ExtrudeCurveStraight" ct=" ExtrudeCurveStraight  Creates a surface by extruding a curve straight along two points that   ..."/><di ky="922" rd="surface_and_polysurface_methods/extrudecurvetapered.htm|ExtrudeCurveTapered" ct=" ExtrudeCurveTapered  Creates a surface by extruding a curve to a taper. Unlike Lofts and Sweeps ..."/><di ky="923" rd="surface_and_polysurface_methods/extrudesurface.htm|ExtrudeSurface" ct=" ExtrudeSurface  Creates a surface or solid by extruding a straight along a path curve.  Synta ..."/><di ky="924" rd="surface_and_polysurface_methods/filletsurfaces.htm|FilletSurfaces" ct=" FilletSurfaces  Create constant radius rolling ball fillets between two surfaces. Note,  this ..."/><di ky="925" rd="surface_and_polysurface_methods/fitsurface.htm|FitSurface" ct=" FitSurface  Reduces the number of surface control points while maintaining the surfaces&apos; same g ..."/><di ky="926" rd="surface_and_polysurface_methods/flipsurface.htm|FlipSurface" ct=" FlipSurface  Returns or changes the normal direction of a surface. This feature can also be fou ..."/><di ky="927" rd="surface_and_polysurface_methods/insertsurfaceknot.htm|InsertSurfaceKnot" ct=" InsertSurfaceKnot  Inserts a knot into a surface object.  Syntax  Rhino.InsertSurfaceKnot ( ..."/><di ky="928" rd="surface_and_polysurface_methods/intersectbreps.htm|IntersectBreps" ct=" IntersectBreps  Intersects a surface or polysurface object with another surface or polysurface  ..."/><di ky="929" rd="surface_and_polysurface_methods/intersectspheres.htm|IntersectSpheres" ct=" IntersectSpheres  Calculates the intersection of two spheres.     Syntax  Rhino.IntersectSp ..."/><di ky="930" rd="surface_and_polysurface_methods/isbox.htm|IsBox" ct=" IsBox  Verifies a polysurface object is a box.  Syntax  Rhino.IsBox (strObject)  Paramete ..."/><di ky="931" rd="surface_and_polysurface_methods/isbrep.htm|IsBrep" ct=" IsBrep  Verifies an object is a Brep, or a boundary representation model, object.  Syntax  ..."/><di ky="932" rd="surface_and_polysurface_methods/isbrepmanifold.htm|IsBrepManifold" ct=" IsBrepManifold  Verifies a polysurface object is manifold.  A polysurface for which every edge  ..."/><di ky="933" rd="surface_and_polysurface_methods/iscone.htm|IsCone" ct=" IsCone  Determines if a surface is a portion of a cone.  Syntax  Rhino.IsCone (strSurface [ ..."/><di ky="934" rd="surface_and_polysurface_methods/iscylinder.htm|IsCylinder" ct=" IsCylinder  Determines if a surface is a portion of a cylinder.  Syntax  Rhino.IsCylinder ( ..."/><di ky="935" rd="surface_and_polysurface_methods/isextrusion.htm|IsExtrusion" ct=" IsExtrusion  Verifies that an object is an extrusion object.  Syntax  Rhino.IsExtrusion (st ..."/><di ky="936" rd="surface_and_polysurface_methods/isparameteronsurface.htm|IsParameterOnSurface" ct=" IsParameterOnSurface  Verifies that a parameter space point is on a trimmed surface, or not on  ..."/><di ky="937" rd="surface_and_polysurface_methods/isplanesurface.htm|IsPlaneSurface" ct=" IsPlaneSurface  Verifies an object is a plane surface. Plane surfaces can be created by the  Pl ..."/><di ky="938" rd="surface_and_polysurface_methods/ispointinsurface.htm|IsPointInSurface" ct=" IsPointInSurface  Verifies that a point is inside a closed surface or polysurface.  Syntax  ..."/></ck>