<?xml version="1.0" encoding="UTF-8"?>
<ck><di ky="591" rd="math_methods/sum.htm|Sum" ct=" Sum  Returns the sum of an array of numbers.  Syntax  Rhino.Sum (arrNumbers)  Parameters ..."/><di ky="592" rd="math_methods/tanh.htm|TanH" ct=" TanH  Returns the hyperbolic tangent of the specified angle.  Syntax  Rhino.TanH (dblAngle) ..."/><di ky="593" rd="math_methods/todegrees.htm|ToDegrees" ct=" ToDegrees  Converts an angle specified in radians to degrees.  Syntax  Rhino.ToDegrees (dbl ..."/><di ky="594" rd="math_methods/toradians.htm|ToRadians" ct=" ToRadians  Converts an angle specified in degrees to radians.  Syntax  Rhino.ToRadians (dbl ..."/><di ky="595" rd="mesh_methods/addmesh.htm|AddMesh" ct=" AddMesh  Adds a mesh object to the document.  Syntax  Rhino.AddMesh (arrVertices, arrFa ..."/><di ky="596" rd="mesh_methods/addplanarmesh.htm|AddPlanarMesh" ct=" AddPlanarMesh  Creates a planar mesh from a closed, planar curve.  Syntax  Rhino.AddPlanarM ..."/><di ky="597" rd="mesh_methods/connectedmeshfaces.htm|ConnectedMeshFaces" ct=" ConnectedMeshFaces  Finds all connected faces of a joined mesh based at a break angle. This   ..."/><di ky="598" rd="mesh_methods/curvemeshintersect.htm|CurveMeshIntersection" ct=" CurveMeshIntersection  Calculates the intersection of a curve object and a mesh object.  Synt ..."/><di ky="599" rd="mesh_methods/deletemeshface.htm|DeleteMeshFace" ct=" DeleteMeshFace  Deletes one or more faces from a mesh object.  Syntax  Rhino.DeleteMeshFace ..."/><di ky="600" rd="mesh_methods/disjointmeshcount.htm|DisjointMeshCount" ct=" DisjointMeshCount  Returns the number of meshes that could be created by calling  SplitDisjoint ..."/><di ky="601" rd="mesh_methods/duplicatemeshborder.htm|DuplicateMeshBorder" ct=" DuplicateMeshBorder  Creates a curve that duplicates a mesh border.  Syntax  Rhino.Duplicat ..."/><di ky="602" rd="mesh_methods/explodemeshes.htm|ExplodeMeshes" ct=" ExplodeMeshes  Explodes a mesh object, or mesh objects,  into submeshes.  A submesh is a collec ..."/><di ky="603" rd="mesh_methods/extractanalysismesh.htm|ExtractAnalysisMesh" ct=" ExtractAnalysisMesh  Extracts the mesh created by the  CurvatureAnalysis   or  DraftAngleAnal ..."/><di ky="604" rd="mesh_methods/extractrendermesh.htm|ExtractRenderMesh" ct=" ExtractRenderMesh  Extracts the render mesh from an object. Surfaces, polysurfaces, meshes,   ..."/><di ky="605" rd="mesh_methods/flipmesh.htm|FlipMesh" ct=" FlipMesh  Reverses the normal direction of a mesh object.  Syntax  Rhino.FlipMesh (strObjec ..."/><di ky="606" rd="mesh_methods/ismesh.htm|IsMesh" ct=" IsMesh  Verifies an object is a mesh object.  Syntax  Rhino.IsMesh (strObject)  Parameter ..."/><di ky="607" rd="mesh_methods/ismeshclosed.htm|IsMeshClosed" ct=" IsMeshClosed  Verifies a mesh object is closed.  Syntax  Rhino.IsMeshClosed (strObject)  ..."/><di ky="608" rd="mesh_methods/ismeshdoubleprecision.htm|IsMeshDoublePrecision" ct=" IsMeshDoublePrecision  Verifies a mesh object contains double-precision vertices.  Syntax  ..."/><di ky="609" rd="mesh_methods/ismeshmanifold.htm|IsMeshManifold" ct=" IsMeshManifold  Verifies a mesh object is manifold.  A mesh for which every edge is shared by a ..."/><di ky="610" rd="mesh_methods/ispointonmesh.htm|IsPointOnMesh" ct=" IsPointOnMesh  Verifies that a point is on a mesh.  Syntax  Rhino.IsPointOnMesh (strObject, ..."/><di ky="611" rd="mesh_methods/joinmeshes.htm|JoinMeshes" ct=" JoinMeshes  Joins two or more mesh object together to form a single mesh object.  Syntax  R ..."/><di ky="612" rd="mesh_methods/mesh_methods.htm|Mesh Methods" ct=" Mesh Methods  The following methods are available for creating, querying or manipulating  mes ..."/><di ky="613" rd="mesh_methods/mesharea.htm|MeshArea" ct=" MeshArea  Returns the approximate area of one or more mesh objects.  Syntax  Rhino.MeshArea ..."/><di ky="614" rd="mesh_methods/meshareacentroid.htm|MeshAreaCentroid" ct=" MeshAreaCentroid  Calculates the area centroid of a mesh object.  Syntax  Rhino.MeshAreaCen ..."/><di ky="615" rd="mesh_methods/meshareamoments.htm|MeshAreaMoments" ct=" MeshAreaMoments  Calculates the area moments of inertia of a mesh object.  For more  informat ..."/><di ky="616" rd="mesh_methods/meshbooleandifference.htm|MeshBooleanDifference" ct=" MeshBooleanDifference  Performs a Boolean difference operation on two sets of input meshes. For ..."/><di ky="617" rd="mesh_methods/meshbooleanintersection.htm|MeshBooleanIntersection" ct=" MeshBooleanIntersection  Performs a Boolean intersection operation on two sets of input meshes. ..."/><di ky="618" rd="mesh_methods/meshbooleansplit.htm|MeshBooleanSplit" ct=" MeshBooleanSplit  Performs a Boolean split operation on two sets of input meshes. For more deta ..."/><di ky="619" rd="mesh_methods/meshbooleanunion.htm|MeshBooleanUnion" ct=" MeshBooleanUnion  Performs a Boolean union operation on a set of input meshes. For more details ..."/><di ky="620" rd="mesh_methods/meshclosestpoint.htm|MeshClosestPoint" ct=" MeshClosestPoint  Returns the point on a mesh that is closest to a test point.  Syntax  Rhi ..."/><di ky="621" rd="mesh_methods/meshcontourpoints.htm|MeshContourPoints" ct=" MeshContourPoints  Returns the vertices of the polyline curves generated by contouring a me ..."/><di ky="622" rd="mesh_methods/meshfacecenters.htm|MeshFaceCenters" ct=" MeshFaceCenters  Returns the center point of each face of a mesh object.    Syntax  Rhino.M ..."/><di ky="623" rd="mesh_methods/meshfacecount.htm|MeshFaceCount" ct=" MeshFaceCount  Returns the total face count of a mesh object.  Syntax  Rhino.MeshFaceCount  ..."/><di ky="624" rd="mesh_methods/meshfacenormals.htm|MeshFaceNormals" ct=" MeshFaceNormals  Returns the face unit normal for each face of a mesh object.    Syntax  Rh ..."/><di ky="625" rd="mesh_methods/meshfaces.htm|MeshFaces" ct=" MeshFaces  Returns the face vertices of a mesh object.  Syntax  Rhino.MeshFaces (strObject, ..."/><di ky="626" rd="mesh_methods/meshfacevertices.htm|MeshFaceVertices" ct=" MeshFaceVertices  Returns the vertex indices of all faces of a mesh object.  Syntax  Rhino. ..."/><di ky="627" rd="mesh_methods/meshhasfacenormals.htm|MeshHasFaceNormals" ct=" MeshHasFaceNormals  Verifies a mesh object has face normals.  Syntax  Rhino.MeshHasFaceNorm ..."/><di ky="628" rd="mesh_methods/meshhashiddenvertices.htm|MeshHasHiddenVertices" ct=" MeshHasHiddenVertices  Verifies that a mesh object has hidden vertices.  Syntax  Rhino.Mesh ..."/><di ky="629" rd="mesh_methods/meshhastexturecoordinates.htm|MeshHasTextureCoordinates" ct=" MeshHasTextureCoordinates  Verifies a mesh object has texture coordinates.  Syntax  Rhino.M ..."/><di ky="630" rd="mesh_methods/meshhasvertexcolors.htm|MeshHasVertexColors" ct=" MeshHasVertexColors  Verifies a mesh object has vertex colors.  Syntax  Rhino.MeshHasVertex ..."/><di ky="631" rd="mesh_methods/meshhasvertexnormals.htm|MeshHasVertexNormals" ct=" MeshHasVertexNormals  Verifies a mesh object has vertex normals.  Syntax  Rhino.MeshHasVert ..."/><di ky="632" rd="mesh_methods/meshhidevertices.htm|MeshHideVertices" ct=" MeshHideVertices  Returns or modifies the hidden vertices of a mesh object. Any mesh faces  t ..."/><di ky="633" rd="mesh_methods/meshmeshintersection.htm|MeshMeshIntersection" ct=" MeshMeshIntersection  Calculates the intersection of a mesh object with another mesh object.  ..."/><di ky="634" rd="mesh_methods/meshnakededgepoints.htm|MeshNakedEdgePoints" ct=" MeshNakedEdgePoints  Identifies the naked edge points of a polygon mesh object. This function s ..."/><di ky="635" rd="mesh_methods/meshobjects.htm|MeshObjects" ct=" MeshObjects  Creates mesh objects from surface, polysurface, and extrusion objects.  Blocks t ..."/><di ky="636" rd="mesh_methods/meshoffset.htm|MeshOffset" ct=" MeshOffset  Makes a new mesh with vertices offset at a distance in the opposite  direction of ..."/><di ky="637" rd="mesh_methods/meshoutline.htm|MeshOutline" ct=" MeshOutline  Creates polyline curve outlines of mesh objects.  Syntax  Rhino.MeshOutline (a ..."/><di ky="638" rd="mesh_methods/meshparameterdensity.htm|MeshParameterDensity" ct=" MeshParameterDensity  Modifies the density of meshes generated with a set of mesh parameters.  ..."/><di ky="639" rd="mesh_methods/meshparameters.htm|MeshParameters" ct=" MeshParameters  Returns or modifies meshing parameters. Note, Rhino&apos;s meshing parameters  are ..."/><di ky="640" rd="mesh_methods/meshpart.htm|MeshPart" ct=" MeshPart  Finds faces from a mesh that are bounded by unwelded or naked edges.  Syntax  Rhi ..."/><di ky="641" rd="mesh_methods/meshquadcount.htm|MeshQuadCount" ct=" MeshQuadCount  Returns the number of quad faces of a mesh object.  Syntax  Rhino.MeshQuadCo ..."/><di ky="642" rd="mesh_methods/meshquadstotriangles.htm|MeshQuadsToTriangles" ct=" MeshQuadsToTriangles  Converts a mesh object&apos;s quad faces to triangles.  Syntax  Rhino.Mesh ..."/><di ky="643" rd="mesh_methods/meshtexturecoordinates.htm|MeshTextureCoordinates" ct=" MeshTextureCoordinates  Returns the normalized 2-D texture coordinates of a mesh object.    S ..."/><di ky="644" rd="mesh_methods/meshtonurb.htm|MeshToNurb" ct=" MeshToNurb  Duplicates each polygon in a polygon mesh with a NURBS surface. The  resulting su ..."/><di ky="645" rd="mesh_methods/meshtrianglecount.htm|MeshTriangleCount" ct=" MeshTriangleCount  Returns the number of triangular faces of a mesh object.  Syntax  Rhino. ..."/><di ky="646" rd="mesh_methods/meshvertexcolors.htm|MeshVertexColors" ct=" MeshVertexColors  Returns or modifies the vertex colors of a mesh object.  Syntax  Rhino.Me ..."/><di ky="647" rd="mesh_methods/meshvertexcount.htm|MeshVertexCount" ct=" MeshVertexCount  Returns the vertex count of a mesh object.  Syntax  Rhino.MeshVertexCount  ..."/><di ky="648" rd="mesh_methods/meshvertexfaces.htm|MeshVertexFaces" ct=" MeshVertexFaces  Returns the mesh faces that share a specified mesh vertex.  Syntax  Rhino. ..."/><di ky="649" rd="mesh_methods/meshvertexnormals.htm|MeshVertexNormals" ct=" MeshVertexNormals  Returns the vertex unit normal for each vertex of a mesh object.    Syntax ..."/><di ky="650" rd="mesh_methods/meshvertices.htm|MeshVertices" ct=" MeshVertices  Returns the vertices of a mesh object.  Syntax  Rhino.MeshVertices (strObject ..."/></ck>