<?xml version="1.0" encoding="UTF-8"?>
<ck><di ky="472" rd="layer_state_methods/savelayerstate.htm|SaveLayerState" ct=" SaveLayerState  Saves the current state of the layers in the document.  Syntax  Rhino.SaveL ..."/><di ky="473" rd="light_methods/adddirectionallight.htm|AddDirectionalLight" ct=" AddDirectionalLight  Adds a new directional light object  to the document.  Syntax  Rhino.A ..."/><di ky="474" rd="light_methods/addlinearlight.htm|AddLinearLight" ct=" AddLinearLight  Adds a new linear light object  to the document.  Syntax  Rhino.AddLinearLi ..."/><di ky="475" rd="light_methods/addpointlight.htm|AddPointLight" ct=" AddPointLight  Adds a new point light object  to the document.  Syntax  Rhino.AddPointLight ..."/><di ky="476" rd="light_methods/addrectangularlight.htm|AddRectangularLight" ct=" AddRectangularLight  Adds a new rectangular light object  to the document.  Syntax  Rhino.A ..."/><di ky="477" rd="light_methods/addspotlight.htm|AddSpotLight" ct=" AddSpotLight  Adds a new spot light object  to the document.  Syntax  Rhino.AddSpotLight (a ..."/><di ky="478" rd="light_methods/enablelight.htm|EnableLight" ct=" EnableLight  Enables or disables a light object.  Syntax  Rhino.EnableLight (strObject [, b ..."/><di ky="479" rd="light_methods/isdirectionallight.htm|IsDirectionalLight" ct=" IsDirectionalLight  Verifies a light object is a directional light.  Syntax  Rhino.IsDirect ..."/><di ky="480" rd="light_methods/islight.htm|IsLight" ct=" IsLight  Verifies an object is a light object.  Syntax  Rhino.IsLight (strObject)  Parame ..."/><di ky="481" rd="light_methods/islightenabled.htm|IsLightEnabled" ct=" IsLightEnabled  Verifies a light object is enabled.  Syntax  Rhino.IsLightEnabled (strObjec ..."/><di ky="482" rd="light_methods/islightreference.htm|IsLightReference" ct=" IsLightReference  Verifies a light object is referenced from another file.  Syntax  Rhino.I ..."/><di ky="483" rd="light_methods/islinearlight.htm|IsLinearLight" ct=" IsLinearLight  Verifies a light object is a linear light.  Syntax  Rhino.IsLinearLight (str ..."/><di ky="484" rd="light_methods/ispointlight.htm|IsPointLight" ct=" IsPointLight  Verifies a light object is a point light.  Syntax  Rhino.IsPointLight (strObj ..."/><di ky="485" rd="light_methods/isrectangularlight.htm|IsRectangularLight" ct=" IsRectangularLight  Verifies a light object is a rectangular light.  Syntax  Rhino.IsRectan ..."/><di ky="486" rd="light_methods/isspotlight.htm|IsSpotLight" ct=" IsSpotLight  Verifies a light object is a spot light.  Syntax  Rhino.IsSpotLight (strObject ..."/><di ky="487" rd="light_methods/light_methods.htm|Light Methods" ct=" Light Methods  The following methods are available for creating, querying or manipulating light ..."/><di ky="488" rd="light_methods/lightcolor.htm|LightColor" ct=" LightColor  Returns or changes the color of a light.  Light colors are represented as RGB color ..."/><di ky="489" rd="light_methods/lightcount.htm|LightCount" ct=" LightCount  Returns the number of light objects in the document.  Syntax  Rhino.LightCount  ..."/><di ky="490" rd="light_methods/lightdirection.htm|LightDirection" ct=" LightDirection  Returns or changes the direction of a light object. This function can be used t ..."/><di ky="491" rd="light_methods/lightlocation.htm|LightLocation" ct=" LightLocation  Returns or changes the location of a light object.  Syntax  Rhino.LightLocat ..."/><di ky="492" rd="light_methods/lightname.htm|LightName" ct=" LightName  Returns or modifies the user-definable name of a light object.  Syntax  Rhino.Li ..."/><di ky="493" rd="light_methods/lightobjects.htm|LightObjects" ct=" LightObjects  Returns the identifier of light objects in the document.  Syntax  Rhino.Light ..."/><di ky="494" rd="light_methods/rectangularlightplane.htm|RectangularLightPlane" ct=" RectangularLightPlane  Returns the plane of a rectangular light object.  Syntax  Rhino.Rect ..."/><di ky="495" rd="light_methods/spotlighthardness.htm|SpotLightHardness" ct=" SpotLightHardness  Returns or changes the hardness of a spot light.  Spotlight hardness control ..."/><di ky="496" rd="light_methods/spotlightradius.htm|SpotLightRadius" ct=" SpotLightRadius  Returns or changes the radius of a spot light.  Syntax  Rhino.SpotLightRad ..."/><di ky="497" rd="light_methods/spotlightshadowintensity.htm|SpotLightShadowIntensity" ct=" SpotLightShadowIntensity  Returns or modifies the shadow intensity of a spot light.  Syntax  ..."/><di ky="498" rd="line_and_plane_methods/distancetoplane.htm|DistanceToPlane" ct=" DistanceToPlane  Returns the distance from a 3-D point to a plane.  Syntax  Rhino.DistanceT ..."/><di ky="499" rd="line_and_plane_methods/evaluateplane.htm|EvaluatePlane" ct=" EvaluatePlane  Evaluates a plane at a U,V parameter.  Syntax  Rhino.EvaluatePlane (arrPlane ..."/><di ky="500" rd="line_and_plane_methods/intersectplanes.htm|IntersectPlanes" ct=" IntersectPlanes  Calculates the intersection of three planes.  Syntax  Rhino.IntersectPlane ..."/><di ky="501" rd="line_and_plane_methods/linearcintersection.htm|LineArcIntersection" ct=" LineArcIntersection  Intersect an infinite line and an arc.  Syntax  Rhino.LineArcIntersect ..."/><di ky="502" rd="line_and_plane_methods/linebetweencurves.htm|LineBetweenCurves" ct=" LineBetweenCurves  Finds a line segment between a pair of curves such that the line segment   ..."/><di ky="503" rd="line_and_plane_methods/lineboxintersection.htm|LineBoxIntersection" ct=" LineBoxIntersection  Intersect an infinite line and an axis-aligned bounding box.    Syntax  ..."/><di ky="504" rd="line_and_plane_methods/linecircleintersection.htm|LineCircleIntersection" ct=" LineCircleIntersection  Intersect an infinite line and a circle.  Syntax  Rhino.LineCircleI ..."/><di ky="505" rd="line_and_plane_methods/lineclosestpoint.htm|LineClosestPoint" ct=" LineClosestPoint  Finds the point on an infinite line that is closest to a test point.  Synta ..."/><di ky="506" rd="line_and_plane_methods/linecurveintersection.htm|LineCurveIntersection" ct=" LineCurveIntersection  Intersect an infinite line and a curve object.  Syntax  Rhino.LineCu ..."/><di ky="507" rd="line_and_plane_methods/linecylinderintersection.htm|LineCylinderIntersection" ct=" LineCylinderIntersection  Calculates the intersection of a line and a cylinder.     Syntax  ..."/><di ky="508" rd="line_and_plane_methods/lineisfartherthan.htm|LineIsFartherThan" ct=" LineIsFartherThan  Determines if the shortest distance from a line to a point or another line i ..."/><di ky="509" rd="line_and_plane_methods/linelineintersection.htm|LineLineIntersection" ct=" LineLineIntersection  Calculates the intersection of two non-parallel lines.  Note, the  two  ..."/><di ky="510" rd="line_and_plane_methods/linemaxdistanceto.htm|LineMaxDistanceTo" ct=" LineMaxDistanceTo  Finds the longest distance between the line, as a finite chord, and  a poi ..."/><di ky="511" rd="line_and_plane_methods/linemeshintersection.htm|LineMeshIntersection" ct=" LineMeshIntersection  Intersect an infinite line and a mesh object.  Syntax  Rhino.LineMesh ..."/><di ky="512" rd="line_and_plane_methods/linemindistanceto.htm|LineMinDistanceTo" ct=" LineMinDistanceTo  Finds the shortest distance between the line, as a finite chord, and  a po ..."/><di ky="513" rd="line_and_plane_methods/lineplane.htm|LinePlane" ct=" LinePlane  Returns a plane that contains the line.  The origin of the plane is at the start of  ..."/><di ky="514" rd="line_and_plane_methods/lineplaneintersection.htm|LinePlaneIntersection" ct=" LinePlaneIntersection  Calculates the intersection of an infinite line and an infinite plane.  ..."/><di ky="515" rd="line_and_plane_methods/linesphereintersection.htm|LineSphereIntersection" ct=" LineSphereIntersection  Calculates the intersection of a line and a sphere.     Syntax  Rhi ..."/><di ky="516" rd="line_and_plane_methods/linetransform.htm|LineTransform" ct=" LineTransform  Transforms a line.  Syntax  Rhino.LineTransform (arrLine, arrXform)  Param ..."/><di ky="517" rd="line_and_plane_methods/moveplane.htm|MovePlane" ct=" MovePlane  Moves the origin of a plane.  Syntax  Rhino.MovePlane (arrPlane, arrOrigin)  P ..."/><di ky="518" rd="line_and_plane_methods/plane_methods.htm|Line and Plane Methods" ct=" Line and Plane Methods  The following methods are available for creating and manipulating lines ..."/><di ky="519" rd="line_and_plane_methods/planeangle.htm|PlaneAngle" ct=" PlaneAngle  Calculates the angle between two points that lie on a given plane.   Syntax  Rh ..."/><di ky="520" rd="line_and_plane_methods/planearcintersection.htm|PlaneArcIntersection" ct=" PlaneArcIntersection  Intersect a plane and an arc.  Syntax  Rhino.PlaneArcIntersection (ar ..."/><di ky="521" rd="line_and_plane_methods/planecircleintersection.htm|PlaneCircleIntersection" ct=" PlaneCircleIntersection  Intersect a plane and a circle.  Syntax  Rhino.PlaneArcIntersectio ..."/><di ky="522" rd="line_and_plane_methods/planeclosestpoint.htm|PlaneClosestPoint" ct=" PlaneClosestPoint  Returns the point on a plane that is closest to a test point.  Syntax  R ..."/><di ky="523" rd="line_and_plane_methods/planecurveintersection.htm|PlaneCurveIntersection" ct=" PlaneCurveIntersection  Intersect an infinite plane and a curve object.  Syntax  Rhino.Plan ..."/><di ky="524" rd="line_and_plane_methods/planeequation.htm|PlaneEquation" ct=" PlaneEquation  Returns the equation of  a plane. The standard equation of a plane with a non-ze ..."/><di ky="525" rd="line_and_plane_methods/planefitfrompoints.htm|PlaneFitFromPoints" ct=" PlaneFitFromPoints  Returns a plane that was fit through an array of 3-D points.  Syntax  R ..."/><di ky="526" rd="line_and_plane_methods/planefromframe.htm|PlaneFromFrame" ct=" PlaneFromFrame  Construct a plane from a point, and two vectors in the plane.  Syntax  Rhin ..."/><di ky="527" rd="line_and_plane_methods/planefromnormal.htm|PlaneFromNormal" ct=" PlaneFromNormal  Creates a plane from an origin point and a normal direction vector.  Syntax ..."/><di ky="528" rd="line_and_plane_methods/planefrompoints.htm|PlaneFromPoints" ct=" PlaneFromPoints  Creates a plane from three non-colinear points.  Syntax  Rhino.PlaneFromPo ..."/><di ky="529" rd="line_and_plane_methods/planeplaneintersection.htm|PlanePlaneIntersection" ct=" PlanePlaneIntersection  Calculates the intersection of two planes.  Syntax  Rhino.PlanePlan ..."/></ck>